package mybatis.dao;

import java.util.List;
import mybatis.model.Grade;
import org.mybatis.cdi.Mapper;

@Mapper
public interface GradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRADE
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRADE
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRADE
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    Grade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRADE
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    List<Grade> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRADE
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    int updateByPrimaryKey(Grade record);
}