package mybatis.model;

public class CourseStudents {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSESTUDENTS.COURSES_ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    private Integer coursesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSESTUDENTS.STUDENTS_STUDENT_ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    private Integer studentsStudentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSESTUDENTS.COURSES_ID
     *
     * @return the value of PUBLIC.COURSESTUDENTS.COURSES_ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public Integer getCoursesId() {
        return coursesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSESTUDENTS.COURSES_ID
     *
     * @param coursesId the value for PUBLIC.COURSESTUDENTS.COURSES_ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public void setCoursesId(Integer coursesId) {
        this.coursesId = coursesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSESTUDENTS.STUDENTS_STUDENT_ID
     *
     * @return the value of PUBLIC.COURSESTUDENTS.STUDENTS_STUDENT_ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public Integer getStudentsStudentId() {
        return studentsStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSESTUDENTS.STUDENTS_STUDENT_ID
     *
     * @param studentsStudentId the value for PUBLIC.COURSESTUDENTS.STUDENTS_STUDENT_ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public void setStudentsStudentId(Integer studentsStudentId) {
        this.studentsStudentId = studentsStudentId;
    }
}