package mybatis.model;

public class Grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRADE.ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRADE.VALUE
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRADE.STUDENT_ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRADE.ID
     *
     * @return the value of PUBLIC.GRADE.ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRADE.ID
     *
     * @param id the value for PUBLIC.GRADE.ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRADE.VALUE
     *
     * @return the value of PUBLIC.GRADE.VALUE
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRADE.VALUE
     *
     * @param value the value for PUBLIC.GRADE.VALUE
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRADE.STUDENT_ID
     *
     * @return the value of PUBLIC.GRADE.STUDENT_ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRADE.STUDENT_ID
     *
     * @param studentId the value for PUBLIC.GRADE.STUDENT_ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}