package mybatis.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.STUDENT_ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.LASTNAME
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.STUDENT_ID
     *
     * @return the value of PUBLIC.STUDENT.STUDENT_ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.STUDENT_ID
     *
     * @param studentId the value for PUBLIC.STUDENT.STUDENT_ID
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.LASTNAME
     *
     * @return the value of PUBLIC.STUDENT.LASTNAME
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.LASTNAME
     *
     * @param lastname the value for PUBLIC.STUDENT.LASTNAME
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.NAME
     *
     * @return the value of PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.NAME
     *
     * @param name the value for PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Mon May 04 21:50:35 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}